name: .NET

on: [pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Hello message
     run: echo "Hello guys"

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --configuration Release

      - name: Publish Application
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./MyApp/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json
  